/**
 * Export utilities for biological sequences
 * Handles conversion to GenBank and SBOL formats
 */

/**
 * Converts experimental design content to GenBank format
 * @param {string} experimentalDesign - The experimental design content
 * @param {string} sequenceName - Name for the sequence
 * @returns {string} - GenBank formatted string
 */
export function convertToGenBank(experimentalDesign, sequenceName = 'synthetic_sequence') {
  // Extract DNA sequences from the experimental design
  const dnaSequences = extractDNASequences(experimentalDesign);
  
  if (dnaSequences.length === 0) {
    return `; No DNA sequences found in experimental design`;
  }
  
  let genbankContent = '';
  
  for (let i = 0; i < dnaSequences.length; i++) {
    const seq = dnaSequences[i];
    const seqName = dnaSequences.length > 1 ? `${sequenceName}_${i+1}` : sequenceName;
    
    // Calculate sequence length and molecule type
    const seqLength = seq.length;
    const molType = determineMoleculeType(seq);
    
    // Create GenBank header
    genbankContent += `LOCUS       ${seqName}                 ${seqLength} ${molType}     circular   SYN 01-JAN-2026\n`;
    genbankContent += `DEFINITION  ${seqName} synthetic construct.\n`;
    genbankContent += `ACCESSION   ${seqName}\n`;
    genbankContent += `VERSION     ${seqName}.1\n`;
    genbankContent += `KEYWORDS    synthetic biology; ${seqName};\n`;
    genbankContent += `SOURCE      synthetic construct\n`;
    genbankContent += `  ORGANISM  synthetic construct\n`;
    genbankContent += `            engineered.\n`;
    genbankContent += `REFERENCE   1  (bases 1 to ${seqLength})\n`;
    genbankContent += `  AUTHORS   SynthBioArchitect\n`;
    genbankContent += `  TITLE     Direct Submission\n`;
    genbankContent += `  JOURNAL   Submitted (01-JAN-2026) SynthBioArchitect\n`;
    genbankContent += `COMMENT     Generated by Synth Bio Architect AI tool.\n`;
    
    // Add features section if available in experimental design
    const features = extractFeaturesFromDesign(experimentalDesign);
    if (features.length > 0) {
      genbankContent += `FEATURES             Location/Qualifiers\n`;
      for (const feature of features) {
        genbankContent += `     ${feature.type}             ${feature.location}\n`;
        genbankContent += `                     /label="${feature.label}"\n`;
        if (feature.note) {
          genbankContent += `                     /note="${feature.note}"\n`;
        }
      }
    }
    
    // Add origin sequence
    genbankContent += `ORIGIN      \n`;
    
    // Format sequence in lines of 60 characters with position numbers
    for (let j = 0; j < seq.length; j += 60) {
      const lineSeq = seq.substring(j, j + 60);
      const position = String(j + 1).padStart(9);
      
      // Format the line with spaces every 10 bases
      let formattedLine = position;
      for (let k = 0; k < lineSeq.length; k += 10) {
        const chunk = lineSeq.substring(k, k + 10);
        formattedLine += ` ${chunk}`;
      }
      
      genbankContent += `${formattedLine}\n`;
    }
    
    genbankContent += `//\n`;
    
    // Add extra newline if there are multiple sequences
    if (i < dnaSequences.length - 1) {
      genbankContent += `\n`;
    }
  }
  
  return genbankContent;
}

/**
 * Extracts DNA sequences from experimental design text
 * @param {string} text - Experimental design content
 * @returns {Array} - Array of DNA sequences found
 */
function extractDNASequences(text) {
  if (!text) return [];
  
  // Look for sequences of ACGT characters (case insensitive)
  // At least 10 characters to be considered a meaningful sequence
  const sequenceRegex = /[ACGTacgt]{10,}/g;
  const matches = text.match(sequenceRegex) || [];
  
  // Remove duplicates while preserving order
  return [...new Set(matches.map(seq => seq.toUpperCase()))];
}

/**
 * Determines molecule type based on sequence characteristics
 * @param {string} sequence - DNA sequence
 * @returns {string} - Molecule type (DNA, RNA, etc.)
 */
function determineMoleculeType(sequence) {
  // For now, assume all sequences are DNA
  // Could be enhanced to detect RNA sequences (with U instead of T)
  return 'DNA';
}

/**
 * Extracts features from experimental design
 * @param {string} design - Experimental design content
 * @returns {Array} - Array of feature objects
 */
function extractFeaturesFromDesign(design) {
  const features = [];
  
  // Look for common feature indicators in the design
  // This is a simplified version - could be enhanced with more sophisticated parsing
  
  // Example: Look for promoter indicators
  if (design.toLowerCase().includes('promoter')) {
    features.push({
      type: 'regulatory',
      location: '1..200',
      label: 'promoter_region',
      note: 'Putative promoter region'
    });
  }
  
  // Example: Look for CDS indicators
  if (design.toLowerCase().includes('coding') || design.toLowerCase().includes('cds')) {
    features.push({
      type: 'CDS',
      location: '201..800',
      label: 'coding_sequence',
      note: 'Coding sequence'
    });
  }
  
  // Example: Look for terminator indicators
  if (design.toLowerCase().includes('terminator') || design.toLowerCase().includes('term')) {
    features.push({
      type: 'terminator',
      location: '801..900',
      label: 'terminator',
      note: 'Transcription terminator'
    });
  }
  
  return features;
}

/**
 * Downloads content as a file
 * @param {string} content - Content to download
 * @param {string} filename - Name of the file
 * @param {string} mimeType - MIME type of the file
 */
export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Downloads experimental design as GenBank file
 * @param {string} experimentalDesign - The experimental design content
 * @param {string} sequenceName - Name for the sequence
 */
export function downloadGenBank(experimentalDesign, sequenceName = 'synthetic_sequence') {
  const genbankContent = convertToGenBank(experimentalDesign, sequenceName);
  downloadFile(genbankContent, `${sequenceName}.gb`, 'text/plain');
}

/**
 * Converts experimental design to SBOL format
 * @param {string} experimentalDesign - The experimental design content
 * @param {string} sequenceName - Name for the sequence
 * @returns {string} - SBOL formatted string
 */
export function convertToSBOL(experimentalDesign, sequenceName = 'synthetic_sequence') {
  // Extract DNA sequences
  const dnaSequences = extractDNASequences(experimentalDesign);
  
  if (dnaSequences.length === 0) {
    return `<!-- No DNA sequences found in experimental design -->`;
  }
  
  // Basic SBOL template - simplified version
  let sbolContent = `<?xml version="1.0" encoding="UTF-8"?>
<sbol:sbol xmlns:sbol="http://sbols.org/v3#" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:dcterms="http://purl.org/dc/terms/elements/1.1/">
  <sbol:Collection sbol:displayId="${sequenceName}_collection" sbol:persistentIdentity="https://synbioarchitect.org/collections/${sequenceName}">
    <sbol:member sbol:ref="https://synbioarchitect.org/designs/${sequenceName}"/>
  </sbol:Collection>\n`;
  
  for (let i = 0; i < dnaSequences.length; i++) {
    const seq = dnaSequences[i];
    const seqName = dnaSequences.length > 1 ? `${sequenceName}_${i+1}` : sequenceName;
    
    sbolContent += `  <sbol:Component sbol:displayId="${seqName}" sbol:persistentIdentity="https://synbioarchitect.org/designs/${seqName}">
    <sbol:type uri="https://identifiers.org/SBO:0000251"/>
    <sbol:role uri="http://identifiers.org/so/SO:0000340"/>
    <sbol:sequences>
      <sbol:Sequence sbol:displayId="${seqName}_seq" sbol:persistentIdentity="https://synbioarchitect.org/sequences/${seqName}">
        <sbol:elements>${seq}</sbol:elements>
        <sbol:encoding uri="https://identifiers.org/so/SO:0000349"/>
      </sbol:Sequence>
    </sbol:sequences>
  </sbol:Component>\n`;
  }
  
  sbolContent += `</sbol:sbol>`;
  
  return sbolContent;
}

/**
 * Downloads experimental design as SBOL file
 * @param {string} experimentalDesign - The experimental design content
 * @param {string} sequenceName - Name for the sequence
 */
export function downloadSBOL(experimentalDesign, sequenceName = 'synthetic_sequence') {
  const sbolContent = convertToSBOL(experimentalDesign, sequenceName);
  downloadFile(sbolContent, `${sequenceName}.xml`, 'application/xml');
}